# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\controlWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1338, 845)
        self.yellowButton = QtWidgets.QPushButton(Form)
        self.yellowButton.setGeometry(QtCore.QRect(730, 471, 116, 55))
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(24)
        self.yellowButton.setFont(font)
        self.yellowButton.setObjectName("yellowButton")
        self.greenButton = QtWidgets.QPushButton(Form)
        self.greenButton.setGeometry(QtCore.QRect(730, 337, 116, 55))
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(24)
        self.greenButton.setFont(font)
        self.greenButton.setObjectName("greenButton")
        self.redButton = QtWidgets.QPushButton(Form)
        self.redButton.setGeometry(QtCore.QRect(730, 404, 116, 55))
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(24)
        self.redButton.setFont(font)
        self.redButton.setObjectName("redButton")
        self.baojing = QtWidgets.QPushButton(Form)
        self.baojing.setGeometry(QtCore.QRect(550, 474, 109, 55))
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(24)
        self.baojing.setFont(font)
        self.baojing.setObjectName("baojing")
        self.shuibeng = QtWidgets.QPushButton(Form)
        self.shuibeng.setGeometry(QtCore.QRect(550, 407, 109, 55))
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(24)
        self.shuibeng.setFont(font)
        self.shuibeng.setObjectName("shuibeng")
        self.fengji = QtWidgets.QPushButton(Form)
        self.fengji.setGeometry(QtCore.QRect(550, 340, 109, 55))
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(24)
        self.fengji.setFont(font)
        self.fengji.setObjectName("fengji")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.yellowButton.setText(_translate("Form", "黄灯"))
        self.greenButton.setText(_translate("Form", "绿灯"))
        self.redButton.setText(_translate("Form", "红灯"))
        self.baojing.setText(_translate("Form", "报警"))
        self.shuibeng.setText(_translate("Form", "水泵"))
        self.fengji.setText(_translate("Form", "风机"))
