# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\桌面\PipeGallery\client\mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(256, 168)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(140, 10, 95, 100))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.fengji = QtWidgets.QPushButton(self.layoutWidget)
        self.fengji.setObjectName("fengji")
        self.verticalLayout_3.addWidget(self.fengji)
        self.shuibeng = QtWidgets.QPushButton(self.layoutWidget)
        self.shuibeng.setObjectName("shuibeng")
        self.verticalLayout_3.addWidget(self.shuibeng)
        self.baojing = QtWidgets.QPushButton(self.layoutWidget)
        self.baojing.setObjectName("baojing")
        self.verticalLayout_3.addWidget(self.baojing)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 10, 95, 100))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.yellowButton = QtWidgets.QPushButton(self.widget)
        self.yellowButton.setObjectName("yellowButton")
        self.verticalLayout.addWidget(self.yellowButton)
        self.redButton = QtWidgets.QPushButton(self.widget)
        self.redButton.setObjectName("redButton")
        self.verticalLayout.addWidget(self.redButton)
        self.greenButton = QtWidgets.QPushButton(self.widget)
        self.greenButton.setObjectName("greenButton")
        self.verticalLayout.addWidget(self.greenButton)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 256, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.fengji.setText(_translate("MainWindow", "风机"))
        self.shuibeng.setText(_translate("MainWindow", "水泵"))
        self.baojing.setText(_translate("MainWindow", "报警"))
        self.yellowButton.setText(_translate("MainWindow", "黄灯"))
        self.redButton.setText(_translate("MainWindow", "红灯"))
        self.greenButton.setText(_translate("MainWindow", "绿灯"))
        self.menu.setTitle(_translate("MainWindow", "管廊控制"))
